public class returnClassAssignmeent {
    public string returnStringMethod(string firstName, string lastName) {
        string fullName = firstName+' '+lastName;
        return fullName;
    }

    public integer addition(integer x, integer y){
        integer z = x+y;
        return z;
    }

    public integer addition(integer x, integer y, integer z, integer m){
        integer sumAll = x+y+z+m;
        return sumAll;
    }
}