string firstVariable= 'this is a first variable';
system.debug(firstVariable);
firstVariable='update variable';
system.debug(firstVariable);


String firstname = 'Alpi';
String lastName = 'Dolg';
String fullname = firstname + ' ' + lastName;
system.debug('full name is' + ' ' + fullname);



string definingStr = 'this is string';

string declarStr;
System.debug(declarStr); 

string strrr = 'RRR';
System.debug(strrr);

