Employee newEmp= new Employee();
newEmp.setName('Walter White');
newEmp.setSalary(20000);
string newEmpName = newEmp.getName();
decimal newEmpSalary = newEmp.getSalary();
system.debug(newEmpName + ' salary is ' + newEmpSalary);

Employee newEmp2= new Employee();
newEmp2.setName('pinkman jesse');
newEmp2.setSalary(600000);
string newEmpName2 = newEmp2.getName();
decimal newEmpSalary2 = newEmp2.getSalary();
system.debug(newEmpName2 + ' salary is ' + newEmpSalary2);