ListDemo2.iterateList2();

listDemo2.friendList();

boolean check1 = ListDemo2.candidateList('leyla');
system.debug('check 1 is ' + check1);

 list<integer> l11 = new list<integer>();
        l11.add(77);
        l11.add(54);
        l11.add(23);
        l11.add(33);
        l11.add(06);
        l11.add(32);
        system.debug('l1 is ' + l11);

 list<integer> l22 = new list<integer>();
    l22.addall(l11);
    l22.add(14);   
    system.debug('l22 is ' + l22);

